name: 'my_ecomm_analytics_project'              #project_name
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  my_ecomm_analytics_project:                   #model materialization

    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table